### ISSUE TITLE
Broken Link to Source Code

### ISSUE THREAD

**Issue by afischer** [brunophilipe/Cakebrew-site#3]
Hey!

On your page, the "Get Source on Github" button links to `https://github.com/brunophilipe/Cakebrew/releases/tag/v1.0.9`, a nonexistent version. Switch it to `https://github.com/brunophilipe/Cakebrew/releases/tag/v1.0.8` and all will be good in the world. Should be just a quick change in [index.php](https://github.com/brunophilipe/Cakebrew-site/blob/master/index.php).

**Comment by potherca** [comment]
Wouldn't it be easier to just link to `https://github.com/brunophilipe/Cakebrew/releases`?
That would save you the work of having to update it everytime :smile_cat:

**Comment by brunophilipe** [comment]
You have a point haha
