### ISSUE TITLE
HTTPS certificate expired

### ISSUE THREAD

**Issue by jrop** [brunophilipe/Cakebrew-site#4]
The certificate expired on the 19th.  I cannot visit https://www.cakebrew.com.  I am currently on mobile (Android).

**Comment by brunophilipe** [comment]
Problem is StartCom is no longer trusted by the major providers, so I have no clue where to get a free trusted certificate at this point.

**Comment by jrop** [comment]
Have you tried LetsEncrypt?

**Comment by brunophilipe** [comment]
I have read about it but the setup seems way too convoluted. Is there a way to just provide a CSR and get a signed certificate like a normal CA?

**Comment by jrop** [comment]
It's not too bad once you have their client installed ([from here](https://certbot.eff.org/)).

You just run:

```sh
$ certbot certonly -d your.domain.tld --standalone
```

If you want to keep your webserver running while obtaining certs, omit the `--sandalone` option.  Once this runs, it will place certs in `/etc/letsencrypt/live/<your.domain.tld>/`.

I agree with you: the LetsEncrypt client seems like it was designed by engineers not too concerned with user experience.  There are [alternate clients out there](https://letsencrypt.org/docs/client-options/) (it is just an ACME client), but I haven't tried them...

**Comment by brunophilipe** [comment]
I went ahead and bought a $9 cert from NameCheap. I guess most people (me included) would rather pay to maintain their current work flow 🙃 

Problem is now fixed. Thanks!

**Comment by jrop** [comment]
For anyone else reading, I did just try [this client (acme.sh)](https://github.com/Neilpang/acme.sh) -- it is everything the default client should be; easy to setup, just a shell script, and just works<sup>TM</sup>.
